// Generate SVG icon URLs for bike categories
// These are inline SVG data URIs representing different bike styles

export const bikeIcons = {
  XC: `data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 200 200'%3E%3Crect fill='%23f8f9fa' width='200' height='200'/%3E%3Ctext x='50' y='80' font-size='60' fill='%23ec4899' font-weight='bold'%3E⚡%3C/text%3E%3Ctext x='20' y='140' font-size='16' fill='%23475569'%3EXC RACER%3C/text%3E%3Ctext x='20' y='160' font-size='12' fill='%239ca3af'%3ESpeed. Efficiency.%3C/text%3E%3C/svg%3E`,

  Trail: `data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 200 200'%3E%3Crect fill='%23f8f9fa' width='200' height='200'/%3E%3Ctext x='50' y='80' font-size='60' fill='%2306b6d4' font-weight='bold'%3E🛤️%3C/text%3E%3Ctext x='15' y='140' font-size='16' fill='%23475569'%3ETRAIL BIKE%3C/text%3E%3Ctext x='20' y='160' font-size='12' fill='%239ca3af'%3EFlow. Fun.%3C/text%3E%3C/svg%3E`,

  Downcountry: `data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 200 200'%3E%3Crect fill='%23f8f9fa' width='200' height='200'/%3E%3Ctext x='45' y='80' font-size='60' fill='%238b5cf6' font-weight='bold'%3E🏔️%3C/text%3E%3Ctext x='10' y='140' font-size='14' fill='%23475569'%3EDOWNCOUNTRY%3C/text%3E%3Ctext x='15' y='160' font-size='12' fill='%239ca3af'%3EDescending.%3C/text%3E%3C/svg%3E`,

  Enduro: `data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 200 200'%3E%3Crect fill='%23f8f9fa' width='200' height='200'/%3E%3Ctext x='50' y='80' font-size='60' fill='%23f97316' font-weight='bold'%3E🚵%3C/text%3E%3Ctext x='25' y='140' font-size='16' fill='%23475569'%3EENDURO%3C/text%3E%3Ctext x='10' y='160' font-size='12' fill='%239ca3af'%3ERugged. Technical.%3C/text%3E%3C/svg%3E`,

  Downhill: `data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 200 200'%3E%3Crect fill='%23f8f9fa' width='200' height='200'/%3E%3Ctext x='50' y='80' font-size='60' fill='%23dc2626' font-weight='bold'%3E🔥%3C/text%3E%3Ctext x='20' y='140' font-size='16' fill='%23475569'%3EDOWNHILL%3C/text%3E%3Ctext x='20' y='160' font-size='12' fill='%239ca3af'%3EBurly Beast.%3C/text%3E%3C/svg%3E`,
};

export const productSpecifications = {
  1: { // Swift XC Pro (XC)
    name: 'Swift XC Pro',
    category: 'XC',
    price: 1499.99,
    description: 'The ultimate cross-country racing machine. Engineered for speed and efficiency on every terrain. Lightweight frame with responsive handling and minimal rolling resistance.',
    geometry: {
      S: { reach: '400mm', stack: '580mm', seatTube: '420mm', headAngle: '71°', seatAngle: '73.5°' },
      M: { reach: '420mm', stack: '595mm', seatTube: '470mm', headAngle: '71°', seatAngle: '73.5°' },
      L: { reach: '440mm', stack: '610mm', seatTube: '520mm', headAngle: '71°', seatAngle: '73.5°' },
      XL: { reach: '460mm', stack: '625mm', seatTube: '570mm', headAngle: '71°', seatAngle: '73.5°' },
    },
    specs: {
      'Frame Material': 'Carbon Fiber 12k',
      'Travel (F/R)': '80mm / 70mm',
      'Wheel Size': '29"',
      'Weight': '1050g (S)',
      'Suspension Type': 'XC Hardtail',
      'Bottom Bracket': 'PF92 Press Fit',
    },
    parts: {
      'Fork': 'Fox 32 SC Performance 100mm',
      'Shock': 'Fox Float DPS 70mm',
      'Drivetrain': 'SRAM NX Eagle 12-speed',
      'Brakes': 'SRAM Level TL Hydraulic Disc',
      'Wheels': 'DT Swiss M1700 Spline 29" Tubeless',
      'Tires': 'Schwalbe Racing Ralph 29x2.1"',
      'Seat': 'WTB Volt Team',
      'Stem': 'Truvativ Stylo Team 70mm',
    },
    features: ['XC Racing Geometry', 'Lightweight Carbon Frame', 'Fox 32 Fork', 'SRAM Eagle Drivetrain', 'Tubeless Ready'],
  },
  2: { // TrailBlazer Elite (Trail)
    name: 'TrailBlazer Elite',
    category: 'Trail',
    price: 2199.99,
    description: 'The perfect all-mountain companion. Versatile geometry lets you flow through tech and pump berms. Balanced suspension design for climbing and descending.',
    geometry: {
      S: { reach: '415mm', stack: '600mm', seatTube: '440mm', headAngle: '66.5°', seatAngle: '73°' },
      M: { reach: '435mm', stack: '615mm', seatTube: '490mm', headAngle: '66.5°', seatAngle: '73°' },
      L: { reach: '455mm', stack: '630mm', seatTube: '540mm', headAngle: '66.5°', seatAngle: '73°' },
      XL: { reach: '475mm', stack: '645mm', seatTube: '590mm', headAngle: '66.5°', seatAngle: '73°' },
    },
    specs: {
      'Frame Material': 'Aluminum 6061-T6',
      'Travel (F/R)': '130mm / 120mm',
      'Wheel Size': '29"',
      'Weight': '1380g (M)',
      'Suspension Type': 'Trail Hardtail',
      'Bottom Bracket': 'Threaded',
    },
    parts: {
      'Fork': 'Fox 34 Performance 130mm',
      'Shock': 'Fox Float DPS Factory 120mm',
      'Drivetrain': 'SRAM GX Eagle 12-speed',
      'Brakes': 'SRAM Guide T Hydraulic Disc',
      'Wheels': 'DT Swiss M1800 Spline 29" Tubeless',
      'Tires': 'Maxxis Forekaster 29x2.4"',
      'Seat': 'WTB Volt Race',
      'Stem': 'Truvativ Stylo Team 50mm',
    },
    features: ['Trail-Tuned Geometry', 'Fox 34 Fork', 'Balanced Suspension', 'Flow-Oriented Design', 'Tubeless Ready'],
  },
  3: { // Alpine Descent (Downcountry)
    name: 'Alpine Descent',
    category: 'Downcountry',
    price: 2799.99,
    description: 'Lightweight descending machine with big capabilities. Engineered for alpine adventures with aggressive geometry and powerful suspension.',
    geometry: {
      S: { reach: '420mm', stack: '605mm', seatTube: '450mm', headAngle: '65°', seatAngle: '72.5°' },
      M: { reach: '440mm', stack: '620mm', seatTube: '500mm', headAngle: '65°', seatAngle: '72.5°' },
      L: { reach: '460mm', stack: '635mm', seatTube: '550mm', headAngle: '65°', seatAngle: '72.5°' },
      XL: { reach: '480mm', stack: '650mm', seatTube: '600mm', headAngle: '65°', seatAngle: '72.5°' },
    },
    specs: {
      'Frame Material': 'Carbon Fiber 11k',
      'Travel (F/R)': '150mm / 140mm',
      'Wheel Size': '29"',
      'Weight': '1420g (M)',
      'Suspension Type': 'Trail Hardtail',
      'Bottom Bracket': 'PF92 Press Fit',
    },
    parts: {
      'Fork': 'Fox 34 Factory 150mm',
      'Shock': 'Fox Float DPS Factory 140mm',
      'Drivetrain': 'SRAM GX Eagle 12-speed',
      'Brakes': 'SRAM Guide R Hydraulic Disc',
      'Wheels': 'Roval Traverse SL 29" Tubeless',
      'Tires': 'Maxxis Dissector 29x2.4"',
      'Seat': 'WTB Volt Race',
      'Stem': 'Truvativ Stylo Team 50mm',
    },
    features: ['Aggressive Geometry', 'Big Suspension Travel', 'Carbon Lightweight', 'Alpine Focused', 'Powerful Descent'],
  },
  4: { // Beast Mode 29 (Enduro)
    name: 'Beast Mode 29',
    category: 'Enduro',
    price: 3499.99,
    description: 'Long-travel enduro workhorse. Handles technical terrain with confidence. Slack geometry and powerful suspension for aggressive all-mountain riding.',
    geometry: {
      S: { reach: '430mm', stack: '615mm', seatTube: '460mm', headAngle: '63°', seatAngle: '72°' },
      M: { reach: '450mm', stack: '630mm', seatTube: '510mm', headAngle: '63°', seatAngle: '72°' },
      L: { reach: '470mm', stack: '645mm', seatTube: '560mm', headAngle: '63°', seatAngle: '72°' },
      XL: { reach: '490mm', stack: '660mm', seatTube: '610mm', headAngle: '63°', seatAngle: '72°' },
    },
    specs: {
      'Frame Material': 'Carbon Fiber 12k',
      'Travel (F/R)': '160mm / 150mm',
      'Wheel Size': '29"',
      'Weight': '1550g (M)',
      'Suspension Type': 'Full Suspension',
      'Bottom Bracket': 'PF92 Press Fit',
    },
    parts: {
      'Fork': 'Fox 36 Factory 160mm',
      'Shock': 'Fox Float X Factory 150mm',
      'Drivetrain': 'SRAM XX1 Eagle 12-speed',
      'Brakes': 'SRAM Code R Hydraulic Disc',
      'Wheels': 'Santa Cruz Hyjack 29" Tubeless',
      'Tires': 'Maxxis Assegai 29x2.5"',
      'Seat': 'WTB Volt Pro',
      'Stem': 'Truvativ Stylo Team 50mm',
    },
    features: ['Full Suspension', 'Slack & Playful', 'Technical Terrain Master', 'Long Travel', 'Aggressive Geometry'],
  },
  5: { // Gravity King DH (Downhill)
    name: 'Gravity King DH',
    category: 'Downhill',
    price: 4299.99,
    description: 'The ultimate burly beast. Purpose-built for gravity. Maximum suspension travel and reinforced frame for extreme downhill racing.',
    geometry: {
      S: { reach: '440mm', stack: '625mm', seatTube: '420mm', headAngle: '62°', seatAngle: '70°' },
      M: { reach: '460mm', stack: '640mm', seatTube: '480mm', headAngle: '62°', seatAngle: '70°' },
      L: { reach: '480mm', stack: '655mm', seatTube: '540mm', headAngle: '62°', seatAngle: '70°' },
      XL: { reach: '500mm', stack: '670mm', seatTube: '600mm', headAngle: '62°', seatAngle: '70°' },
    },
    specs: {
      'Frame Material': 'Carbon Fiber 12k',
      'Travel (F/R)': '200mm / 200mm',
      'Wheel Size': '29"',
      'Weight': '1800g (M)',
      'Suspension Type': 'Full Suspension DH',
      'Bottom Bracket': 'PF92 Press Fit',
    },
    parts: {
      'Fork': 'Fox 38 Factory 200mm',
      'Shock': 'Fox DHX Factory 200mm',
      'Drivetrain': 'SRAM GX Eagle 12-speed',
      'Brakes': 'SRAM Code RSC Hydraulic Disc',
      'Wheels': 'DT Swiss FR 1950 29" Tubeless',
      'Tires': 'Maxxis Minion DHF/DHR 29x2.5"',
      'Seat': 'WTB Volt Pro DH',
      'Stem': 'Truvativ Stylo DH 35mm',
    },
    features: ['Maximum Travel', 'Gravity Focused', 'DH Specific Geometry', 'Double Crown Ready', 'Extreme Downhill'],
  },
  6: { // Cross Lite (XC)
    name: 'Cross Lite',
    category: 'XC',
    price: 1299.99,
    description: 'Lightweight cross-country bike perfect for fast-paced XC racing. Efficient power transfer and snappy handling on any terrain.',
    geometry: {
      S: { reach: '395mm', stack: '575mm', seatTube: '410mm', headAngle: '71.5°', seatAngle: '73.5°' },
      M: { reach: '415mm', stack: '590mm', seatTube: '460mm', headAngle: '71.5°', seatAngle: '73.5°' },
      L: { reach: '435mm', stack: '605mm', seatTube: '510mm', headAngle: '71.5°', seatAngle: '73.5°' },
      XL: { reach: '455mm', stack: '620mm', seatTube: '560mm', headAngle: '71.5°', seatAngle: '73.5°' },
    },
    specs: {
      'Frame Material': 'Aluminum 6061-T6',
      'Travel (F/R)': '80mm / 70mm',
      'Wheel Size': '29"',
      'Weight': '1150g (M)',
      'Suspension Type': 'XC Hardtail',
      'Bottom Bracket': 'Threaded',
    },
    parts: {
      'Fork': 'Fox 32 Performance 80mm',
      'Shock': 'Fox Float DPS Performance 70mm',
      'Drivetrain': 'SRAM NX Eagle 12-speed',
      'Brakes': 'SRAM Level T Hydraulic Disc',
      'Wheels': 'DT Swiss M1700 Spline 29" Tubeless',
      'Tires': 'Schwalbe Racing Ralph 29x2.1"',
      'Seat': 'WTB Volt Team',
      'Stem': 'Truvativ Stylo 70mm',
    },
    features: ['Budget XC Racing', 'Lightweight Frame', 'Responsive Handling', 'Great Value', 'Fast & Efficient'],
  },
  7: { // Trailmaster 27.5 (Trail)
    name: 'Trailmaster 27.5',
    category: 'Trail',
    price: 1899.99,
    description: 'Nimble 27.5" trail bike for technical terrain. Perfect for riders who love playful geometry and tight steering. Excellent for technical single track.',
    geometry: {
      S: { reach: '405mm', stack: '590mm', seatTube: '430mm', headAngle: '67°', seatAngle: '73.5°' },
      M: { reach: '425mm', stack: '605mm', seatTube: '480mm', headAngle: '67°', seatAngle: '73.5°' },
      L: { reach: '445mm', stack: '620mm', seatTube: '530mm', headAngle: '67°', seatAngle: '73.5°' },
      XL: { reach: '465mm', stack: '635mm', seatTube: '580mm', headAngle: '67°', seatAngle: '73.5°' },
    },
    specs: {
      'Frame Material': 'Aluminum 6061-T6',
      'Travel (F/R)': '120mm / 110mm',
      'Wheel Size': '27.5"',
      'Weight': '1300g (M)',
      'Suspension Type': 'Trail Hardtail',
      'Bottom Bracket': 'Threaded',
    },
    parts: {
      'Fork': 'RockShox Recon RL 120mm',
      'Shock': 'RockShox Deluxe RT 110mm',
      'Drivetrain': 'SRAM SX Eagle 12-speed',
      'Brakes': 'SRAM Level T Hydraulic Disc',
      'Wheels': 'Roval Traverse 27.5" Tubeless',
      'Tires': 'Maxxis Foreskater 27.5x2.35"',
      'Seat': 'WTB Volt Race',
      'Stem': 'Truvativ Stylo 50mm',
    },
    features: ['Playful Geometry', '27.5" Agility', 'Technical Terrain Ready', 'Great Handling', 'Fun Factor'],
  },
  8: { // Enduro Plus (Enduro)
    name: 'Enduro Plus',
    category: 'Enduro',
    price: 3199.99,
    description: 'All-mountain enduro shredder with ample suspension travel. Slack geometry and confident handling for big mountain adventures and technical descents.',
    geometry: {
      S: { reach: '425mm', stack: '610mm', seatTube: '455mm', headAngle: '63.5°', seatAngle: '72°' },
      M: { reach: '445mm', stack: '625mm', seatTube: '505mm', headAngle: '63.5°', seatAngle: '72°' },
      L: { reach: '465mm', stack: '640mm', seatTube: '555mm', headAngle: '63.5°', seatAngle: '72°' },
      XL: { reach: '485mm', stack: '655mm', seatTube: '605mm', headAngle: '63.5°', seatAngle: '72°' },
    },
    specs: {
      'Frame Material': 'Carbon Fiber 11k',
      'Travel (F/R)': '155mm / 145mm',
      'Wheel Size': '29"',
      'Weight': '1480g (M)',
      'Suspension Type': 'Full Suspension',
      'Bottom Bracket': 'PF92 Press Fit',
    },
    parts: {
      'Fork': 'Fox 34 Factory 155mm',
      'Shock': 'Fox Float DPS Factory 145mm',
      'Drivetrain': 'SRAM GX Eagle 12-speed',
      'Brakes': 'SRAM Guide R Hydraulic Disc',
      'Wheels': 'Roval Traverse SL 29" Tubeless',
      'Tires': 'Maxxis Dissector 29x2.4"',
      'Seat': 'WTB Volt Pro',
      'Stem': 'Truvativ Stylo Team 50mm',
    },
    features: ['Full Suspension', 'Slack Geometry', 'Big Travel', 'Playful Handling', 'Alpine Ready'],
  },
};
